#---------------------------------#
#      general configuration      #
#---------------------------------#

environment:
  nuget_api_key:
    secure: MrSRAszIaYtCfFJMtNgV4a8tftGNQOyFgYz5m7jVm8d3bFSSlFKFCMTRFAWCfmbp

# version format
version: 0.1.{build}

# Build worker image (VM template)
image: Visual Studio 2015

# clone directory
clone_folder: c:\projects\VL.OpenCV

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.1.{build}-alpha"
  assembly_file_version: "{version}"


install:
  appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Debug

build:
  project: src\VL.OpenCV.sln      # path to Visual Studio solution or project
  publish_nuget: false             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: false     # generate and publish NuGet symbol packages
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts

before_build:
  - cd src
  - nuget restore -DisableParallelProcessing
  

after_build:
  - cd..
  - nuget pack appveyor\VL.OpenCV.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - nuget setApiKey %nuget_api_key%
  - nuget push C:\projects\VL.OpenCV\VL.OpenCV%APPVEYOR_BUILD_VERSION%.nupkg -Source https://api.nuget.org/v3/index.json
    
artifacts:
  - path: '*.nupkg'
    type: NuGetPackage
  
#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

  # Email
  - provider: Email
    to:
      - ravazquez@gmail.com
    subject: 'VL.OpenCV Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_status_changed: true